services:
  - type: web
    name: juristbot
    env: python
    plan: free
    region: oregon
    branch: main
    
    # Configurações de build
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p app/data app/logs
    
    # ✅ CORREÇÃO: Comando direto sem cd
    startCommand: python main.py
    
    # Variáveis de ambiente
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: juristbot
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: BOT_NAME
        value: "JuristBot 2.0"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "8443"
      - key: RENDER_WEBHOOK_URL
        fromService:
          type: web
          name: juristbot
          property: url

version: "1"
