services:
  - type: web
    name: juristbot
    env: python
    plan: free
    region: oregon
    branch: main
    
    # Build simplificado
    buildCommand: |
      echo "🔧 Instalando dependências..."
      pip install -r requirements.txt
      echo "📁 Criando diretórios..."
      mkdir -p app/data app/logs
      echo "✅ Build completo!"
    

startCommand: python -m app.main

    
    # Variáveis de ambiente
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: juristbot
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: BOT_NAME
        value: "JuristBot 2.0"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "10000"

version: "1"
